apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiny-web.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "tiny-web.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
