replicaCount: 1

image:
  repository: ghcr.io/tanujagopalasetti/tiny-web
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

serviceMonitor:
  enabled: true
  # must match kube-prometheus-stack release name
  releaseLabel: monitoring
  interval: 15s
  path: /metrics

resources: {}
